jest.unmock('../Counter.js');

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var Counter = require('../Counter.js');

//Generated by ReactTGN on Fri Apr 22 2016 17:57:33 GMT-0500 (CDT)
describe('Counter', function () {

	it('input 0', function () {

		//Rendering component with input
		var input = JSON.parse("\"{}\"");
		var counter = ReactDOMServer.renderToStaticMarkup(
			<Counter {...input} />
		);
		//Expectations
		expect(counter).toEqual("<button>Click me! Number of clicks: 0</button>");

	});


});
