jest.unmock('../ExampleApplication.js');

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var ExampleApplication = require('../ExampleApplication.js');

//Generated by ReactTGN on Fri Apr 22 2016 17:57:50 GMT-0500 (CDT)
describe('ExampleApplication', function () {

	it('input 0', function () {

		//Rendering component with input
		var input = JSON.parse("\"{}\"");
		var exampleApplication = ReactDOMServer.renderToStaticMarkup(
			<ExampleApplication {...input} />
		);
		//Expectations
		expect(exampleApplication).toEqual("<p>React has been successfully running for NaN.0 seconds.</p>");

	});

	it('input 1', function () {

		//Rendering component with input
		var input = JSON.parse("{\"elapsed\":0}");
		var exampleApplication = ReactDOMServer.renderToStaticMarkup(
			<ExampleApplication {...input} />
		);
		//Expectations
		expect(exampleApplication).toEqual("<p>React has been successfully running for 0.0 seconds.</p>");

	});


});
