jest.unmock('../Example.js');

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var Example = require('../Example.js');

//Generated by ReactTGN on Fri Apr 22 2016 18:02:04 GMT-0500 (CDT)
describe('Example', function () {

	it('input 0', function () {

		//Rendering component with input
		var input = JSON.parse("\"{}\"");
		var example = ReactDOMServer.renderToStaticMarkup(
			<Example {...input} />
		);
		//Expectations
		expect(example).toEqual("<div class=\"example\"><div class=\"modal fade\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><button type=\"button\" class=\"close\">×</button><h3>Hello, Bootstrap!</h3></div><div class=\"modal-body\">This is a React component powered by jQuery and Bootstrap!</div><div class=\"modal-footer\"><a class=\"btn-default\">Cancel</a><a class=\"btn-primary\">OK</a></div></div></div></div><a class=\"btn-default\">Open modal</a></div>");

	});


});
