jest.unmock('../Quadratic.js');

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var Quadratic = require('../Quadratic.js');

//Generated by ReactTGN on Fri Apr 22 2016 18:26:12 GMT-0500 (CDT)
describe('Quadratic', function () {

	it('input 0', function () {

		//Rendering component with input
		var input = JSON.parse("\"{}\"");
		var quadratic = ReactDOMServer.renderToStaticMarkup(
			<Quadratic {...input} />
		);
		//Expectations
		expect(quadratic).toEqual("<div><strong><em>ax</em><sup>2</sup> + <em>bx</em> + <em>c</em> = 0</strong><h4>Solve for <em>x</em>:</h4><p><label>a: </label><br/><label>b: </label><br/><label>c: </label><br/>x: <strong>NaN, NaN</strong></p></div>");

	});


});
