jest.unmock('../LightBulb.js');

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var LightBulb = require('../LightBulb.js');

//Generated by ReactTGN on Thu Apr 21 2016 23:00:27 GMT-0500 (CDT)
describe('LightBulb', function () {

	it('input 0', function () {

		//Rendering component with input
		var input = JSON.parse("{\"isOn\":0}");
		var lightBulb = ReactDOMServer.renderToStaticMarkup(
			<LightBulb {...input} />
		);
		//Expectations
		expect(lightBulb).toEqual("<div>Light is off</div>");

	});

	it('input 1', function () {

		//Rendering component with input
		var input = JSON.parse("{\"isOn\":-1}");
		var lightBulb = ReactDOMServer.renderToStaticMarkup(
			<LightBulb {...input} />
		);
		//Expectations
		expect(lightBulb).toEqual("<div>Light is on</div>");

	});


});
